### ISSUE TITLE
TypeError: range indices must be integers or slices, not str

### ISSUE THREAD

**Issue by dr-ashu-geno** [RajLabMSSM/snakeSV#3]
Hi there.
Thank you for developing snakeSV.

I installed snakeSV using bioconda but every time I run it (whether on my own samples or as a test_run), it throws the following error:

Building DAG of jobs...
InputFunctionException in rule genotype_01 in file /DIR/snakeSV/workflow/rules/genotype.smk, line 116:
Error:
  TypeError: range indices must be integers or slices, not str
Wildcards:
  sample=HG002_tiny
  chrom=1
Traceback:
  File "/DIR/snakeSV/workflow/rules/genotype.smk", line 127, in <lambda>

Do you have any ideas on how to solve this issue?

Thanks in advance,

**Comment by ricardovialle** [comment]
Hi @dr-ashu-geno,

Sorry about the delay in addressing this issue. The problem was occurring because of some Python version conflicts in the bioconda recipe. 

Please try reinstalling with the upgraded version `v0.8` and specifying the Python version as follows (using mamba is recommended to speed up the environment solving):

`mamba create -n snakesv_env -c conda-forge -c bioconda snakesv=0.8 python=3.11.6`

Please let me know if you still have issues.

Thanks,
Ricardo
